import { apiDownload, apiFetch, apiFetchArray, type AnyObj } from '../api';

type Id = string | number;

/** Server inventory, monitoring, Docker, and custom-update API surface. */
export const serversApi = {
  getServers: (environmentId?: string) => apiFetchArray<AnyObj>(`/servers${environmentId ? `?environment_id=${encodeURIComponent(environmentId)}` : ''}`),
  getServer: (id: Id) => apiFetch<AnyObj>(`/servers/${id}`),
  createServer: (data: AnyObj) => apiFetch<AnyObj>('/servers', { method: 'POST', body: data }),
  updateServer: (id: Id, data: AnyObj) => apiFetch(`/servers/${id}`, { method: 'PUT', body: data }),
  deleteServer: (id: Id) => apiFetch(`/servers/${id}`, { method: 'DELETE' }),
  testConnection: (id: Id) => apiFetch(`/servers/${id}/test`, { method: 'POST' }),
  testNewServerConnection: (data: AnyObj) => apiFetch<{ connected: boolean; error?: string }>('/servers/connection-test', { method: 'POST', body: data }),
  resetServerHostKey: (id: Id) => apiFetch(`/servers/${id}/reset-host-key`, { method: 'POST' }),
  autoGroupByTags: () => apiFetch('/servers/auto-group-by-tags', { method: 'POST' }),
  setServerGroup: (serverId: Id, groupId: Id | null) => apiFetch(`/servers/${serverId}/group`, { method: 'PUT', body: { group_id: groupId } }),
  setServersGroup: (serverIds: Id[], groupId: Id | null) => apiFetch('/servers/group/bulk', { method: 'PUT', body: { server_ids: serverIds, group_id: groupId } }),
  getServerGroups: (environmentId?: string) => apiFetchArray<AnyObj>(`/servers/groups${environmentId ? `?environment_id=${encodeURIComponent(environmentId)}` : ''}`),
  createServerGroup: (name: string, color?: string, parentId?: Id | null, environmentId?: string) => apiFetch('/servers/groups', { method: 'POST', body: { name, color, parent_id: parentId ?? null, ...(environmentId ? { environment_id: environmentId } : {}) } }),
  updateServerGroup: (id: Id, name: string, color?: string) => apiFetch(`/servers/groups/${id}`, { method: 'PUT', body: { name, color } }),
  deleteServerGroup: (id: Id) => apiFetch(`/servers/groups/${id}`, { method: 'DELETE' }),
  setGroupParent: (groupId: Id, parentId: Id | null) => apiFetch(`/servers/groups/${groupId}/parent`, { method: 'PUT', body: { parent_id: parentId } }),
  exportServers: (format: 'json' | 'csv') => apiDownload(`/servers/export?format=${format}`, `servers.${format}`),
  importServers: (servers: AnyObj[]) => apiFetch('/servers/import', { method: 'POST', body: { servers } }),
  getServerInfo: (id: Id, force = false) => apiFetch<AnyObj>(`/servers/${id}/info${force ? '?force=1' : ''}`),
  getServerServices: (id: Id) => apiFetch<AnyObj>(`/servers/${id}/services`),
  getServerUpdates: (id: Id, force = false) => apiFetch<AnyObj>(`/servers/${id}/updates${force ? '?force=1' : ''}`),
  getServerHistory: (id: Id) => apiFetchArray<AnyObj>(`/servers/${id}/history`),
  getServerNotes: (id: Id) => apiFetch<{ notes: string }>(`/servers/${id}/notes`),
  saveServerNotes: (id: Id, notes: string) => apiFetch(`/servers/${id}/notes`, { method: 'PUT', body: { notes } }),
  getServerAlertSettings: (id: Id) => apiFetch<AnyObj>(`/servers/${id}/alert-settings`),
  saveServerAlertSettings: (id: Id, data: AnyObj) => apiFetch(`/servers/${id}/alert-settings`, { method: 'PUT', body: data }),
  getServerDocker: (id: Id, force = false) => apiFetch<AnyObj>(`/servers/${id}/docker${force ? '?force=1' : ''}`),
  restartContainer: (id: Id, container: string) => apiFetch(`/servers/${id}/docker/${container}/restart`, { method: 'POST' }),
  getContainerLogs: (id: Id, container: string, tail = 200) => apiFetch<{ logs: string }>(`/servers/${id}/docker/${encodeURIComponent(container)}/logs?tail=${tail}`),
  checkImageUpdates: (id: Id) => apiFetch(`/servers/${id}/docker/image-updates`),
  getCachedImageUpdates: (id: Id) => apiFetch(`/servers/${id}/docker/image-updates/cached`),
  getCustomUpdateTasks: (serverId: Id) => apiFetchArray<AnyObj>(`/servers/${serverId}/custom-updates`),
  createCustomUpdateTask: (serverId: Id, data: AnyObj) => apiFetch(`/servers/${serverId}/custom-updates`, { method: 'POST', body: data }),
  updateCustomUpdateTask: (serverId: Id, taskId: Id, data: AnyObj) => apiFetch(`/servers/${serverId}/custom-updates/${taskId}`, { method: 'PUT', body: data }),
  deleteCustomUpdateTask: (serverId: Id, taskId: Id) => apiFetch(`/servers/${serverId}/custom-updates/${taskId}`, { method: 'DELETE' }),
  runCustomUpdateTask: (serverId: Id, taskId: Id) => apiFetch(`/servers/${serverId}/custom-updates/${taskId}/run`, { method: 'POST' }),
  checkCustomUpdateTask: (serverId: Id, taskId: Id) => apiFetch(`/servers/${serverId}/custom-updates/${taskId}/check`, { method: 'POST' }),
  getDockerCompose: (id: Id, path: string) => apiFetch<{ content: string }>(`/servers/${id}/docker/compose?path=${encodeURIComponent(path)}`),
  writeDockerCompose: (id: Id, path: string, content: string) => apiFetch(`/servers/${id}/docker/compose/write`, { method: 'POST', body: { path, content } }),
  composeAction: (id: Id, path: string, action: string) => apiFetch(`/servers/${id}/docker/compose/action`, { method: 'POST', body: { path, action } }),
  deleteComposeStack: (id: Id, path: string) => apiFetch(`/servers/${id}/docker/compose/stack?path=${encodeURIComponent(path)}`, { method: 'DELETE' }),
};
