import { apiDownload, apiFetch, apiFetchArray, type AnyObj } from '../api';

type Id = string | number;

/** Server inventory, monitoring, Docker, and custom-update API surface. */
export const serversApi = {
  getServers: (environmentId?: string) => apiFetchArray<AnyObj>(`/servers${environmentId ? `?environment_id=${encodeURIComponent(environmentId)}` : ''}`),
  getServer: (id: Id) => apiFetch<AnyObj>(`/servers/${id}`),
  createServer: (data: AnyObj) => apiFetch<AnyObj>('/servers', { method: 'POST', body: data, environmentId: typeof data.environment_id === 'string' ? data.environment_id : undefined }),
  updateServer: (id: Id, data: AnyObj) => apiFetch(`/servers/${id}`, { method: 'PUT', body: data }),
  deleteServer: (id: Id, environmentId?: string) => apiFetch(`/servers/${id}`, { method: 'DELETE', environmentId }),
  previewServerUpdates: (id: Id, environmentId?: string) => apiFetch<{
    checked_at: string;
    plan: null | { strategy: string; service_ownership?: Array<{package:string; units:string[] | null}>; changes: Array<{ action: 'upgrade' | 'install' | 'remove'; package: string; current_version: string | null; candidate_version: string | null }> };
  }>(`/servers/${id}/updates/preview`, { timeoutMs: 120_000, environmentId }),
  testConnection: (id: Id) => apiFetch(`/servers/${id}/test`, { method: 'POST' }),
  testNewServerConnection: (data: AnyObj) => apiFetch<{ connected: boolean; error?: string }>('/servers/connection-test', { method: 'POST', body: data, environmentId: typeof data.environment_id === 'string' ? data.environment_id : undefined }),
  resetServerHostKey: (id: Id) => apiFetch(`/servers/${id}/reset-host-key`, { method: 'POST' }),
  autoGroupByTags: () => apiFetch('/servers/auto-group-by-tags', { method: 'POST' }),
  setServerGroup: (serverId: Id, groupId: Id | null) => apiFetch(`/servers/${serverId}/group`, { method: 'PUT', body: { group_id: groupId } }),
  setServersGroup: (serverIds: Id[], groupId: Id | null, environmentId?: string) => apiFetch('/servers/group/bulk', { method: 'PUT', body: { server_ids: serverIds, group_id: groupId }, environmentId }),
  getServerGroups: (environmentId?: string) => apiFetchArray<AnyObj>(`/servers/groups${environmentId ? `?environment_id=${encodeURIComponent(environmentId)}` : ''}`),
  createServerGroup: (name: string, color?: string, parentId?: Id | null, environmentId?: string) => apiFetch('/servers/groups', { method: 'POST', body: { name, color, parent_id: parentId ?? null, ...(environmentId ? { environment_id: environmentId } : {}) }, environmentId }),
  updateServerGroup: (id: Id, name: string, color?: string, environmentId?: string, parentId?: Id | null) => apiFetch(`/servers/groups/${id}`, { method: 'PUT', body: { name, color, ...(parentId !== undefined ? { parent_id: parentId } : {}) }, environmentId }),
  deleteServerGroup: (id: Id) => apiFetch(`/servers/groups/${id}`, { method: 'DELETE' }),
  setGroupParent: (groupId: Id, parentId: Id | null, environmentId?: string) => apiFetch(`/servers/groups/${groupId}/parent`, { method: 'PUT', body: { parent_id: parentId }, environmentId }),
  exportServers: (format: 'json' | 'csv') => apiDownload(`/servers/export?format=${format}`, `servers.${format}`),
  importServers: (servers: AnyObj[]) => apiFetch('/servers/import', { method: 'POST', body: { servers } }),
  getServerInfo: (id: Id, force = false) => apiFetch<AnyObj>(`/servers/${id}/info${force ? '?force=1' : ''}`),
  getServerServices: (id: Id) => apiFetch<AnyObj>(`/servers/${id}/services`),
  getServerUpdates: (id: Id, force = false) => apiFetch<AnyObj>(`/servers/${id}/updates${force ? '?force=1' : ''}`),
  getServerHistory: (id: Id) => apiFetchArray<AnyObj>(`/servers/${id}/history`),
  getServerNotes: (id: Id) => apiFetch<{ notes: string; revision: number; author: string | null; updated_at: string | null }>(`/servers/${id}/notes`),
  saveServerNotes: (id: Id, notes: string, revision: number) => apiFetch<{ notes: string; revision: number; author: string | null; updated_at: string | null }>(`/servers/${id}/notes`, { method: 'PUT', body: { notes, revision } }),
  getServerAlertSettings: (id: Id) => apiFetch<AnyObj>(`/servers/${id}/alert-settings`),
  saveServerAlertSettings: (id: Id, data: AnyObj) => apiFetch(`/servers/${id}/alert-settings`, { method: 'PUT', body: data }),
  getServerDocker: (id: Id, force = false) => apiFetch<AnyObj>(`/servers/${id}/docker${force ? '?force=1' : ''}`),
  restartContainer: (id: Id, container: string) => apiFetch(`/servers/${id}/docker/${container}/restart`, { method: 'POST' }),
  getContainerLogs: (id: Id, container: string, tail = 200) => apiFetch<{ logs: string }>(`/servers/${id}/docker/${encodeURIComponent(container)}/logs?tail=${tail}`),
  checkImageUpdates: (id: Id) => apiFetch(`/servers/${id}/docker/image-updates`),
  getCachedImageUpdates: (id: Id) => apiFetch(`/servers/${id}/docker/image-updates/cached`),
  setImageCheckExclusion: (id: Id, image: string, excluded: boolean) => apiFetch(`/servers/${id}/docker/image-check-exclusions`, { method: 'PUT', body: { image, excluded } }),
  getCustomUpdateTasks: (serverId: Id) => apiFetchArray<AnyObj>(`/servers/${serverId}/custom-updates`),
  createCustomUpdateTask: (serverId: Id, data: AnyObj) => apiFetch(`/servers/${serverId}/custom-updates`, { method: 'POST', body: data }),
  updateCustomUpdateTask: (serverId: Id, taskId: Id, data: AnyObj) => apiFetch(`/servers/${serverId}/custom-updates/${taskId}`, { method: 'PUT', body: data }),
  deleteCustomUpdateTask: (serverId: Id, taskId: Id) => apiFetch(`/servers/${serverId}/custom-updates/${taskId}`, { method: 'DELETE' }),
  runCustomUpdateTask: (serverId: Id, taskId: Id) => apiFetch(`/servers/${serverId}/custom-updates/${taskId}/run`, { method: 'POST' }),
  previewCustomUpdateTask: (serverId: Id, data: AnyObj) => apiFetch<{current_version: string | null; last_version: string | null; has_update: boolean}>(`/servers/${serverId}/custom-updates/preview`, { method: 'POST', body: data, timeoutMs: 120000 }),
  getCustomUpdateSnapshotTarget: (serverId: Id) => apiFetch<{available: boolean; node_name?: string; vm_id?: number; guest_type?: string}>(`/servers/${serverId}/custom-updates/snapshot-target`),
  checkCustomUpdateTask: (serverId: Id, taskId: Id) => apiFetch(`/servers/${serverId}/custom-updates/${taskId}/check`, { method: 'POST' }),
  getDockerCompose: (id: Id, path: string) => apiFetch<{ content: string }>(`/servers/${id}/docker/compose?path=${encodeURIComponent(path)}`),
  writeDockerCompose: (id: Id, path: string, content: string) => apiFetch(`/servers/${id}/docker/compose/write`, { method: 'POST', body: { path, content } }),
  composeAction: (id: Id, path: string, action: string) => apiFetch(`/servers/${id}/docker/compose/action`, { method: 'POST', body: { path, action } }),
  deleteComposeStack: (id: Id, path: string) => apiFetch(`/servers/${id}/docker/compose/stack?path=${encodeURIComponent(path)}`, { method: 'DELETE' }),
};
