import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Network, Plus } from 'lucide-react';
import { apiFetch } from '@/lib/api';
import { useUi } from '@/lib/store';
import { showToast } from '@/lib/toast';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { PageHeader } from '@/components/ui/page-header';

interface Subnet { id: string; name: string; cidr: string; gateway?: string; dns_servers?: string[]; vlan_id?: number | null; bridge?: string; description?: string; reservation_count?: number; usable_address_count?: number; free_address_count?: number }
export function NetworksPage() {
  const environmentId = useUi(state => state.environmentId); const [createOpen, setCreateOpen] = useState(false);
  const query = useQuery({ queryKey: ['ipam', 'subnets', environmentId], queryFn: () => apiFetch<Subnet[]>(`/ipam/subnets?environment_id=${encodeURIComponent(environmentId)}`) }); const subnets = Array.isArray(query.data) ? query.data : [];
  return <div className="space-y-6"><PageHeader title="Netzwerke" description="IP-Adressmanagement pro Umgebung – nach dem NetBox-Prinzip: Netz auswählen, Belegung sehen und Bereiche reservieren." actions={<Button onClick={() => setCreateOpen(true)}><Plus />Netzwerk anlegen</Button>} />
    <Card><CardHeader className="border-b"><CardTitle className="flex items-center gap-2 text-base"><Network className="h-4 w-4" />Netzwerkliste <span className="rounded bg-muted px-2 py-0.5 text-xs font-normal text-muted-foreground">{subnets.length}</span></CardTitle></CardHeader><CardContent className="p-0">{subnets.length === 0 ? <p className="p-8 text-sm text-muted-foreground">Noch keine Netzwerke. Lege ein IPv4-Netz mit Gateway, DNS, VLAN und Bridge an.</p> : <div className="divide-y">{subnets.map(network => <Link key={network.id} to="/networks/$id" params={{ id: network.id }} className="grid gap-3 px-5 py-4 transition-colors hover:bg-muted/40 md:grid-cols-[minmax(220px,1.5fr)_minmax(160px,1fr)_minmax(170px,1fr)_120px]"><div><div className="font-medium">{network.name}</div><div className="mt-1 font-mono text-xs text-muted-foreground">{network.cidr}</div>{network.description && <p className="mt-1.5 text-xs text-muted-foreground">{network.description}</p>}</div><div className="text-sm text-muted-foreground"><div className="font-medium text-foreground">{network.vlan_id ? `VLAN ${network.vlan_id}` : 'Kein VLAN'}</div><div className="mt-1 font-mono text-xs">{network.bridge || 'Keine Bridge'}</div></div><div className="text-sm"><div className="font-medium tabular-nums">{network.free_address_count ?? '—'} frei</div><div className="mt-1 text-xs text-muted-foreground">{network.reservation_count || 0} von {network.usable_address_count ?? '—'} reserviert</div></div><div className="self-center text-right text-sm font-medium text-brand">Öffnen →</div></Link>)}</div>}</CardContent></Card><CreateSubnetDialog open={createOpen} onOpenChange={setCreateOpen} environmentId={environmentId} /></div>;
}
function CreateSubnetDialog({ open, onOpenChange, environmentId }: { open: boolean; onOpenChange: (open: boolean) => void; environmentId: string }) { const qc = useQueryClient(); const [name, setName] = useState(''); const [cidr, setCidr] = useState(''); const [gateway, setGateway] = useState(''); const [vlan, setVlan] = useState(''); const [bridge, setBridge] = useState(''); const [dns, setDns] = useState(''); const [description, setDescription] = useState(''); const create = useMutation({ mutationFn: () => apiFetch('/ipam/subnets', { method: 'POST', body: { environment_id: environmentId, name, cidr, gateway, vlan_id: vlan, bridge, description, dns_servers: dns.split(',').map(value => value.trim()).filter(Boolean) } }), onSuccess: () => { showToast('Netzwerk angelegt.', 'success'); onOpenChange(false); void qc.invalidateQueries({ queryKey: ['ipam'] }); }, onError: (error: Error) => showToast(error.message, 'error') }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Netzwerk anlegen</DialogTitle><DialogDescription>Definiert ein routbares IPv4-Netz für VM-Vorlagen und IP-Reservierungen.</DialogDescription></DialogHeader><form className="grid gap-4 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); create.mutate(); }}><Field label="Name"><Input required value={name} onChange={event => setName(event.target.value)} placeholder="Produktion" /></Field><Field label="IPv4-CIDR"><Input required value={cidr} onChange={event => setCidr(event.target.value)} placeholder="10.20.10.0/24" /></Field><Field label="Gateway"><Input value={gateway} onChange={event => setGateway(event.target.value)} placeholder="10.20.10.1" /></Field><Field label="VLAN-ID"><Input value={vlan} onChange={event => setVlan(event.target.value)} inputMode="numeric" placeholder="2010" /></Field><Field label="Bridge"><Input value={bridge} onChange={event => setBridge(event.target.value)} placeholder="vmbr0" /></Field><Field label="DNS-Server"><Input value={dns} onChange={event => setDns(event.target.value)} placeholder="10.20.10.2, 1.1.1.1" /></Field><div className="sm:col-span-2"><Field label="Beschreibung"><Input value={description} onChange={event => setDescription(event.target.value)} placeholder="Applikationsnetz für Produktion" /></Field></div><DialogFooter className="sm:col-span-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Abbrechen</Button><Button type="submit" disabled={create.isPending}>Netzwerk anlegen</Button></DialogFooter></form></DialogContent></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
