import {test,expect,type Page,type Locator} from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const shots=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../test-results/design-layout');
async function login(page:Page){await page.goto('/login');await page.evaluate(async()=>{const body=JSON.stringify({username:'e2e-admin',password:'E2e-password-2026!'});let r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body});if(!r.ok)r=await fetch('/api/auth/setup',{method:'POST',headers:{'Content-Type':'application/json'},body});const data=await r.json();if(!data.token)throw Error('Isolated authentication failed');localStorage.setItem('shipyard_token',data.token);});await page.goto('/');}
async function shot(page:Page,name:string){fs.mkdirSync(shots,{recursive:true});await page.screenshot({path:path.join(shots,name+'.png'),fullPage:true,animations:'disabled'});}
async function inViewport(page: Page, locator: Locator) {
  await expect(locator).toBeVisible();
  // Entry animations change dialog transforms after they become visible.
  // Retry geometry without scrolling, while still rejecting persistent overflow.
  await expect(async () => {
    const bounds = await locator.boundingBox();
    expect(bounds).not.toBeNull();
    expect(bounds!.y).toBeGreaterThanOrEqual(0);
    expect(bounds!.x).toBeGreaterThanOrEqual(0);
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height);
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  }).toPass({ timeout: 5000 });
}

test('tablet navigation remains readable at intermediate widths',async({page})=>{await login(page);for(const width of [768,820,1024]){await page.setViewportSize({width,height:900});await page.goto('/settings/notifications');if(width<1024){await page.getByRole('button',{name:'Open navigation',exact:true}).click();}const nav=page.getByRole('navigation',{name:'Main navigation'});const a=nav.getByRole('link',{name:'Infrastructure',exact:true}),b=nav.getByRole('link',{name:'Automations',exact:true});await inViewport(page,a);await inViewport(page,b);const x=await a.boundingBox(),y=await b.boundingBox();expect(x!.y+x!.height).toBeLessThanOrEqual(y!.y+1);await shot(page,'navigation-'+width);if(width<1024)await page.getByRole('button',{name:'Close navigation',exact:true}).first().click();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);}});

test('notification sections preserve drafts when collapsed and save explicitly',async({page})=>{await login(page);await page.setViewportSize({width:390,height:844});await page.goto('/settings/notifications');const section=page.locator('[data-notification-section]').filter({has:page.locator('summary').filter({hasText:'Configure webhook'})});const summary=section.locator('summary');await expect(summary).toBeVisible();await expect(section.getByRole('textbox',{name:'Webhook URL'})).toBeHidden();await shot(page,'notifications-390');expect(await page.evaluate(()=>document.documentElement.scrollHeight)).toBeLessThan(1500);await summary.click();const field=section.getByRole('textbox',{name:'Webhook URL'});await field.fill('https://example.invalid/design-review');await summary.click();await expect(summary).toContainText('Unsaved changes');await summary.click();await expect(field).toHaveValue('https://example.invalid/design-review');await section.getByRole('button',{name:'Discard webhook changes'}).click();await expect(summary).not.toContainText('Unsaved changes');await summary.click();await page.setViewportSize({width:1440,height:900});await shot(page,'notifications-1440');});

test('VM wizard and maintenance keep actions visible while their body scrolls',async({page})=>{await login(page);await page.route('**/api/opentofu/proxmox-connections?*',r=>r.fulfill({json:[{id:'design',name:'Design platform',endpoint:'https://design.example',environment_id:'default'}]}));await page.route('**/api/opentofu/proxmox-connections/design/vm-catalog*',r=>r.fulfill({json:{nodes:[{node:'pve-design'}],storages:[],bridges:[],isos:[],templates:[]}}));for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===1440?900:844});await page.goto('/deployments');await page.getByRole('button',{name:'Create managed VM',exact:true}).first().click();await page.getByRole('button',{name:'Continue',exact:true}).click();if(width===1440)await page.getByRole('navigation',{name:'VM setup steps'}).getByRole('button').nth(2).click();else await page.getByRole('combobox',{name:'VM setup step'}).selectOption('2');const dialog=page.getByRole('dialog');await inViewport(page,dialog.getByRole('button',{name:'Continue',exact:true}));await dialog.locator('[data-dialog-body]').evaluate(el=>{el.scrollTop=el.scrollHeight;});await inViewport(page,dialog.getByRole('button',{name:'Continue',exact:true}));await inViewport(page,dialog.getByRole('heading',{name:'Add Proxmox VM',exact:true}));await shot(page,'vm-wizard-'+width);if(width<640){await page.getByRole('combobox',{name:'VM setup step'}).selectOption('4');await inViewport(page,dialog.getByRole('button',{name:'Save VM definition',exact:true}));expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await shot(page,'vm-review-'+width);}await page.keyboard.press('Escape');await page.goto('/operations?section=maintenance');await page.getByRole('button',{name:'Add maintenance window',exact:true}).first().click();await inViewport(page,page.getByRole('dialog').getByRole('button',{name:'Schedule maintenance window',exact:true}));await page.getByRole('dialog').locator('[data-dialog-body]').evaluate(el=>{el.scrollTop=el.scrollHeight;});await inViewport(page,page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}));await shot(page,'maintenance-'+width);await page.keyboard.press('Escape');}});

test('quick run exposes its action immediately and schedules have a contextual header',async({page})=>{await login(page);await page.goto('/playbooks#tab=runs');await inViewport(page,page.getByRole('button',{name:'Run',exact:true}));await expect(page.getByText('Select a playbook and run it.',{exact:true})).toHaveCount(0);await shot(page,'quick-run-1440');await page.setViewportSize({width:390,height:844});await page.goto('/playbooks#tab=schedules');await expect(page.getByRole('button',{name:'New Playbook',exact:true})).toHaveCount(0);await inViewport(page,page.getByRole('button',{name:'New Schedule',exact:true}));await shot(page,'schedules-390');});
